"""Migración inicial

Revision ID: 36da3a6e8fb9
Revises: 
Create Date: 2025-07-14 10:57:34.255690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36da3a6e8fb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito_producto', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('carrito_producto_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'carritos', ['id_carrito'], ['id'])

    with op.batch_alter_table('detalle_orden', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detalle_orden_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ordenes', ['id_orden'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña_hash', sa.String(length=200), nullable=False))
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('contraseña_hash')

    with op.batch_alter_table('detalle_orden', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detalle_orden_ibfk_1'), 'ordenes', ['id_orden'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('carrito_producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('carrito_producto_ibfk_1'), 'carritos', ['id_carrito'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
